export interface DiagramStyleConfig {
  id: string;
  name: string;
  badge?: string;
  description: string;
  tags: string[];

  // Layout geometry (used by astToGraph)
  // CRITICAL RULE: In every style, ALL blocks (start, end, process, io, decision, loop, subprogram)
  // have strictly the EXACT SAME WIDTH: nodeWidth.
  // Expansion is ONLY vertical (blocks grow taller when text has multiple lines).
  nodeWidth: number;          // Uniform width for ALL blocks in diagram (range 195 - 245)
  baseHeight: number;         // Base height for process & subprogram blocks (range 50 - 64)
  startBaseHeight: number;    // Base vertical height for "Начало" and "Конец" (usually narrow: 32 - 40, standard: 50 - 56)
  rhombusBaseHeight: number;  // Base vertical height for Decision rhombus (flat: 40 - 48, standard: 54 - 58)
  yMargin: number;            // Vertical gap between blocks: 14 - 24
  xSep: number;               // Horizontal branch spacing: 50 - 64

  // Block geometry proportions
  ioSkew: number;                // Parallelogram slant offset (range 14 - 22)
  loopHexTip: number;            // Loop hexagon tip depth (range 18 - 26)
  processRx: number;             // Corner radius on process blocks (0 for sharp ГОСТ, 2-3 for soft)
  subprogramStripeOffset: number; // Subprogram vertical stripe distance from edges (standard 14-16)

  // Stroke and typography
  strokeColor?: string;          // Default '#18181b', '#4b5563' for draw.io gray slate, '#000000' for pure black
  strokeWidth: number;           // Standard 1.2 - 2.0
  fontSize: number;              // Standard 13.5 - 15.5
  fontWeight: '400' | '500' | '600' | '700'; // Font weight inside nodes
  arrowSize: number;             // Arrowhead size (standard 5 - 7)

  // Style characteristics
  isRough?: boolean;             // For "Троечник ночью": hand-drawn sketch jitter effect
  suggestedFont?: string;        // Suggested font pairing
}

export const DIAGRAM_STYLES: DiagramStyleConfig[] = [
  {
    id: 'drawio_default',
    name: 'draw.io / Diagrams.net (По умолчанию)',
    badge: 'Скриншот 1',
    description: 'Эталонный вид схем из веб-редактора draw.io. Четкие черные контуры 1.4px, узкий овал «Начало/Конец» (38px), плоские ромбы и шрифт Arial.',
    tags: ['draw.io', 'Студент', 'Популярный'],
    nodeWidth: 215,
    baseHeight: 58,
    startBaseHeight: 38,
    rhombusBaseHeight: 46,
    yMargin: 20,
    xSep: 60,
    ioSkew: 18,
    loopHexTip: 24,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#18181b',
    strokeWidth: 1.4,
    fontSize: 14.5,
    fontWeight: '500',
    arrowSize: 6,
    suggestedFont: '"Arial", sans-serif'
  },
  {
    id: 'drawio_slate_gray',
    name: 'draw.io Серый монохром (Slate Gray)',
    badge: 'Скриншот 2',
    description: 'Характерный серый контур (#4b5563) из draw.io. Узкий овал 36px, ультра-плоский ромб 44px, мягкие стрелки и шрифт Inter.',
    tags: ['Серый', 'draw.io', 'Лаконичный'],
    nodeWidth: 215,
    baseHeight: 58,
    startBaseHeight: 36,
    rhombusBaseHeight: 44,
    yMargin: 20,
    xSep: 60,
    ioSkew: 18,
    loopHexTip: 24,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#4b5563',
    strokeWidth: 1.5,
    fontSize: 14.5,
    fontWeight: '500',
    arrowSize: 6,
    suggestedFont: '"Inter", sans-serif'
  },
  {
    id: 'word_coursework',
    name: 'Курсовая работа в Word (Times)',
    badge: 'Скриншот 3',
    description: 'Классический отчет в Microsoft Word. Черные линии 1.5px, ультра-узкое «Начало/Конец» (34px), плоский ромб 48px и академический Times New Roman / PT Serif.',
    tags: ['Word', 'Курсовая', 'Засечки'],
    nodeWidth: 220,
    baseHeight: 60,
    startBaseHeight: 34,
    rhombusBaseHeight: 48,
    yMargin: 20,
    xSep: 60,
    ioSkew: 18,
    loopHexTip: 24,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#000000',
    strokeWidth: 1.5,
    fontSize: 14.5,
    fontWeight: '600',
    arrowSize: 6,
    suggestedFont: '"PT Serif", serif'
  },
  {
    id: 'visio_technical',
    name: 'Microsoft Visio (Инженерный)',
    badge: 'Скриншот 4',
    description: 'Инженерная схема из шаблона Visio. Тонкие линии 1.4px, ультра-узкое начало 34px, плоские ромбы 46px и технический Consolas.',
    tags: ['Visio', 'Инженерный', 'Consolas'],
    nodeWidth: 220,
    baseHeight: 60,
    startBaseHeight: 34,
    rhombusBaseHeight: 46,
    yMargin: 22,
    xSep: 60,
    ioSkew: 18,
    loopHexTip: 24,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#18181b',
    strokeWidth: 1.4,
    fontSize: 14,
    fontWeight: '500',
    arrowSize: 6,
    suggestedFont: '"Consolas", monospace'
  },
  {
    id: 'classic_gost',
    name: 'Классический ЕСКД ГОСТ 19.701-90',
    badge: 'Канон ГОСТ',
    description: 'Эталонный полноразмерный ГОСТ. Все блоки единой ширины 220px, полная высота начала 56px, толщина линий 1.5 мм, моноширинный шрифт JetBrains Mono.',
    tags: ['ГОСТ', 'Стандарт', 'Канон'],
    nodeWidth: 220,
    baseHeight: 64,
    startBaseHeight: 56,
    rhombusBaseHeight: 58,
    yMargin: 22,
    xSep: 60,
    ioSkew: 18,
    loopHexTip: 26,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#18181b',
    strokeWidth: 1.5,
    fontSize: 15,
    fontWeight: '600',
    arrowSize: 6,
    suggestedFont: '"JetBrains Mono", monospace'
  },
  {
    id: 'gost_compact_start',
    name: 'ГОСТ с плоским «Начало/Конец» (34px)',
    badge: 'ГОСТ / Компакт',
    description: 'Строгий чертежный ГОСТ, но терминаторы «Начало» и «Конец» сплюснуты по вертикали (34px) для экономии высоты страницы отчета.',
    tags: ['ГОСТ', 'Узкое начало', 'Чертеж'],
    nodeWidth: 220,
    baseHeight: 62,
    startBaseHeight: 34,
    rhombusBaseHeight: 50,
    yMargin: 20,
    xSep: 60,
    ioSkew: 18,
    loopHexTip: 26,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#18181b',
    strokeWidth: 1.5,
    fontSize: 14.5,
    fontWeight: '600',
    arrowSize: 6,
    suggestedFont: '"PT Mono", monospace'
  },
  {
    id: 'compact_a4',
    name: 'Компактный для отчета А4',
    badge: '1 страница',
    description: 'Уменьшенные вертикальные зазоры (14px) и высота блоков (50px, начало 32px). Создан, чтобы многострочные алгоритмы умещались на один лист без разрывов.',
    tags: ['Компактный', 'А4', 'Плотный'],
    nodeWidth: 205,
    baseHeight: 50,
    startBaseHeight: 32,
    rhombusBaseHeight: 42,
    yMargin: 14,
    xSep: 52,
    ioSkew: 16,
    loopHexTip: 20,
    processRx: 0,
    subprogramStripeOffset: 14,
    strokeColor: '#18181b',
    strokeWidth: 1.3,
    fontSize: 13.5,
    fontWeight: '500',
    arrowSize: 5,
    suggestedFont: '"Roboto", sans-serif'
  },
  {
    id: 'wide_expressions',
    name: 'Широкий формат (245px)',
    badge: 'Широкий',
    description: 'Увеличенная ширина ВСЕХ блоков до 245px. Удобен для длинных математических выражений, формул и вызовов методов.',
    tags: ['Широкий', 'Формулы', 'Математика'],
    nodeWidth: 245,
    baseHeight: 60,
    startBaseHeight: 36,
    rhombusBaseHeight: 48,
    yMargin: 22,
    xSep: 64,
    ioSkew: 20,
    loopHexTip: 26,
    processRx: 0,
    subprogramStripeOffset: 16,
    strokeColor: '#18181b',
    strokeWidth: 1.5,
    fontSize: 14.5,
    fontWeight: '500',
    arrowSize: 6,
    suggestedFont: '"JetBrains Mono", monospace'
  },
  {
    id: 'narrow_two_columns',
    name: 'Узкая колонка (195px)',
    badge: '2 колонки',
    description: 'Уменьшенная ширина всех блоков 195px. Позволяет аккуратно верстать блок-схему в двухколоночный отчет или журнальную статью.',
    tags: ['Узкий', 'Колонки', 'Статья'],
    nodeWidth: 195,
    baseHeight: 56,
    startBaseHeight: 34,
    rhombusBaseHeight: 44,
    yMargin: 18,
    xSep: 50,
    ioSkew: 16,
    loopHexTip: 20,
    processRx: 0,
    subprogramStripeOffset: 14,
    strokeColor: '#18181b',
    strokeWidth: 1.3,
    fontSize: 13.5,
    fontWeight: '500',
    arrowSize: 5,
    suggestedFont: '"Arial", sans-serif'
  },
  {
    id: 'pascalabc_academic',
    name: 'PascalABC.NET / Первый курс',
    badge: '1 курс',
    description: 'Академический стиль лабораторных работ по основам алгоритмизации. Четкие формы, Consolas 14px, узкое начало 36px.',
    tags: ['1 курс', 'Основы', 'Consolas'],
    nodeWidth: 215,
    baseHeight: 58,
    startBaseHeight: 36,
    rhombusBaseHeight: 46,
    yMargin: 20,
    xSep: 58,
    ioSkew: 18,
    loopHexTip: 24,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#18181b',
    strokeWidth: 1.4,
    fontSize: 14,
    fontWeight: '500',
    arrowSize: 6,
    suggestedFont: '"Consolas", monospace'
  },
  {
    id: 'dia_linux',
    name: 'Dia Diagram Editor (Linux / СПО)',
    badge: 'Linux',
    description: 'Аутентичный стиль открытого редактора Dia для Linux. Чистые линии 1.4px, узкий овал 38px, плоские шестиугольники циклов и PT Sans.',
    tags: ['Dia', 'Linux', 'СПО'],
    nodeWidth: 215,
    baseHeight: 58,
    startBaseHeight: 38,
    rhombusBaseHeight: 46,
    yMargin: 20,
    xSep: 60,
    ioSkew: 18,
    loopHexTip: 24,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#18181b',
    strokeWidth: 1.4,
    fontSize: 14,
    fontWeight: '500',
    arrowSize: 6,
    suggestedFont: '"PT Sans", sans-serif'
  },
  {
    id: 'flat_diamonds',
    name: 'Плоские ромбы условий',
    badge: 'Плоский ромб',
    description: 'Ромбы решений сделаны максимально приплюснутыми по вертикали (40px) при стандартной ширине блоков 220px. Ветвления не растягивают схему.',
    tags: ['Плоский ромб', 'Компакт', 'Логика'],
    nodeWidth: 220,
    baseHeight: 58,
    startBaseHeight: 36,
    rhombusBaseHeight: 40,
    yMargin: 18,
    xSep: 60,
    ioSkew: 18,
    loopHexTip: 24,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#18181b',
    strokeWidth: 1.4,
    fontSize: 14.5,
    fontWeight: '500',
    arrowSize: 6,
    suggestedFont: '"Inter", sans-serif'
  },
  {
    id: 'cad_drafting',
    name: 'Чертежный Компас / ГОСТ 2.304',
    badge: 'Компас-3D',
    description: 'Стиль чертежных САПР (Компас-3D, AutoCAD). Тонкие резкие линии 1.2px, чертежный шрифт ГОСТ, узкое начало 34px, острые параллелограммы.',
    tags: ['САПР', 'Компас', 'Чертеж'],
    nodeWidth: 220,
    baseHeight: 60,
    startBaseHeight: 34,
    rhombusBaseHeight: 46,
    yMargin: 22,
    xSep: 60,
    ioSkew: 20,
    loopHexTip: 24,
    processRx: 0,
    subprogramStripeOffset: 14,
    strokeColor: '#18181b',
    strokeWidth: 1.2,
    fontSize: 14,
    fontWeight: '500',
    arrowSize: 5.5,
    suggestedFont: '"GOST Type A", monospace'
  },
  {
    id: 'contrast_black',
    name: 'Контрастный черный (Линии 2.0px)',
    badge: 'Печать',
    description: 'Насыщенные глубокие черные контуры 2.0px и полужирный шрифт. Гарантирует безупречную четкость при распечатке на бумаге и в PDF.',
    tags: ['Печать', 'Контраст', 'Черный'],
    nodeWidth: 220,
    baseHeight: 62,
    startBaseHeight: 38,
    rhombusBaseHeight: 50,
    yMargin: 22,
    xSep: 62,
    ioSkew: 18,
    loopHexTip: 26,
    processRx: 0,
    subprogramStripeOffset: 16,
    strokeColor: '#000000',
    strokeWidth: 2.0,
    fontSize: 15,
    fontWeight: '700',
    arrowSize: 7,
    suggestedFont: '"Roboto", sans-serif'
  },
  {
    id: 'school_ege',
    name: 'Школьная информатика / ЕГЭ (Поляков)',
    badge: 'ЕГЭ / Школа',
    description: 'Стиль учебных пособий К. Полякова и Л. Босовой. Шрифт Trebuchet / Verdana, ясные пропорции, высота начала 40px, заметные ветки ДА/НЕТ.',
    tags: ['Школа', 'ЕГЭ', 'Поляков'],
    nodeWidth: 220,
    baseHeight: 62,
    startBaseHeight: 40,
    rhombusBaseHeight: 50,
    yMargin: 22,
    xSep: 62,
    ioSkew: 18,
    loopHexTip: 24,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#18181b',
    strokeWidth: 1.6,
    fontSize: 15,
    fontWeight: '600',
    arrowSize: 6.5,
    suggestedFont: '"Trebuchet MS", sans-serif'
  },
  {
    id: 'minimal_lab',
    name: 'Минималистичная лабораторная',
    badge: 'Минимализм',
    description: 'Изящные тонкие линии 1.2px, узкий овал 34px, аккуратный легкий гротеск PT Astra Sans / Inter 14px.',
    tags: ['Тонкие линии', 'Минимализм', 'Чистый'],
    nodeWidth: 215,
    baseHeight: 56,
    startBaseHeight: 34,
    rhombusBaseHeight: 44,
    yMargin: 18,
    xSep: 56,
    ioSkew: 16,
    loopHexTip: 22,
    processRx: 0,
    subprogramStripeOffset: 14,
    strokeColor: '#27272a',
    strokeWidth: 1.2,
    fontSize: 14,
    fontWeight: '400',
    arrowSize: 5,
    suggestedFont: '"PT Astra Sans", sans-serif'
  },
  {
    id: 'college_tech',
    name: 'Техникум / Колледж (Calibri)',
    badge: 'Колледж',
    description: 'Повседневный отчет студента технического колледжа. Шрифт Calibri, узкое начало 36px, мягкие скругления углов процесса (2px), плоские ромбы 46px.',
    tags: ['Колледж', 'Calibri', 'Мягкий'],
    nodeWidth: 215,
    baseHeight: 58,
    startBaseHeight: 36,
    rhombusBaseHeight: 46,
    yMargin: 20,
    xSep: 60,
    ioSkew: 18,
    loopHexTip: 24,
    processRx: 2,
    subprogramStripeOffset: 15,
    strokeColor: '#18181b',
    strokeWidth: 1.4,
    fontSize: 14.5,
    fontWeight: '500',
    arrowSize: 6,
    suggestedFont: '"Calibri", sans-serif'
  },
  {
    id: 'slacker_night',
    name: 'Троечник ночью перед сдачей',
    badge: 'Скетч в 4 утра',
    description: 'Живой вид скетча: легкая неровность линий (jitter), рукописный шрифт Bad Script, иллюзия быстрого рисования от руки в спешке.',
    tags: ['Скетч', 'Троечник', 'Живой'],
    nodeWidth: 225,
    baseHeight: 64,
    startBaseHeight: 38,
    rhombusBaseHeight: 50,
    yMargin: 22,
    xSep: 60,
    ioSkew: 22,
    loopHexTip: 26,
    processRx: 1,
    subprogramStripeOffset: 16,
    strokeColor: '#18181b',
    strokeWidth: 1.7,
    fontSize: 15.5,
    fontWeight: '600',
    arrowSize: 7,
    isRough: true,
    suggestedFont: '"Bad Script", cursive'
  },
  {
    id: 'modern_it_fira',
    name: 'Современный IT-бакалавриат (Fira Code)',
    badge: 'IT-кодинг',
    description: 'Стиль современных программистов. Моноширинный Fira Code / JetBrains Mono, чистые линии 1.4px, узкое начало 36px, плоский ромб 46px.',
    tags: ['IT', 'Fira Code', 'Современный'],
    nodeWidth: 220,
    baseHeight: 58,
    startBaseHeight: 36,
    rhombusBaseHeight: 46,
    yMargin: 20,
    xSep: 60,
    ioSkew: 18,
    loopHexTip: 24,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#18181b',
    strokeWidth: 1.4,
    fontSize: 14,
    fontWeight: '500',
    arrowSize: 6,
    suggestedFont: '"Fira Code", monospace'
  },
  {
    id: 'warm_vintage_blueprint',
    name: 'Архивный ГОСТ СССР (Теплый чертеж)',
    badge: 'Винтажный ГОСТ',
    description: 'Теплый оттенок контуров (#27272a), чертежный ГОСТ шрифт, высота терминаторов 50px, аутентичный вид советских технических справочников.',
    tags: ['Винтаж', 'ГОСТ', 'Архив'],
    nodeWidth: 220,
    baseHeight: 62,
    startBaseHeight: 50,
    rhombusBaseHeight: 54,
    yMargin: 22,
    xSep: 60,
    ioSkew: 18,
    loopHexTip: 26,
    processRx: 0,
    subprogramStripeOffset: 15,
    strokeColor: '#27272a',
    strokeWidth: 1.5,
    fontSize: 14.5,
    fontWeight: '600',
    arrowSize: 6,
    suggestedFont: '"GOST Type B", monospace'
  }
];

export function getDiagramStyle(id?: string): DiagramStyleConfig {
  if (!id) return DIAGRAM_STYLES[0];
  const found = DIAGRAM_STYLES.find(s => s.id === id);
  return found || DIAGRAM_STYLES[0];
}
